### ISSUE TITLE
Hard Code SlackClient Version Requirements

### ISSUE THREAD

**Issue by minitriga** [jeremyschulman/slackapptk#18]
Looks like the slack client changed a bit in 2.6 which means this library breaks a little. hardcoding 2.5 in requirements seems to fix this for me.

**Comment by jeremyschulman** [comment]
You are correct. In fact I had made this change in my local dev system but neglected to PR. My bad.  If you'd like to make that PR please do.

**Comment by jeremyschulman** [comment]
At some point I do plan to "rebase" this project to the latest client from Slack. This would be a new major version for slackapptk repo as well.

**Comment by jeremyschulman** [comment]
resolved in 1.0.0
